<?php
////////////////////////////////////////////////////
//
// WeatherOffice
//
// http://www.sourceforge.net/projects/weatheroffice
//
// Copyright (C) 04/2007 Mathias Zuckermann &
//			 Bernhard Heibler
//
// See COPYING for license info
//
////////////////////////////////////////////////////
// Declare all text strings that we need,
// in German.
$GLOBALS['text'] = array (
  'weatherstation_in' => 'Wetterstation in ',
  'current_values' => 'Aktuelle Werte',
  'last_24_hours' => 'Letzte 24 Stunden',
  'daily_overview' => 'Tages&uuml;bersicht',
  'weekly_overview' => 'Wochen&uuml;bersicht',
  'monthly_overview' => 'Monats&uuml;bersicht',
  'Monthly' => 'Monatliche',
  'yearly_overview' => 'Jahres&uuml;bersicht',
  'yearly_overview_graph' => 'Jahresübersicht',
  'partial_values' => 'Vorl&auml;ufig bis zum',
  'current_values' => 'Aktuelle Messwerte',
  'tendency' => 'Tendenz',
  'temperature' => 'Temperatur',
  'Temperatures' => 'Temperaturen',
  'humidity' => 'Luftfeuchtigkeit',
  'pressure' => 'Luftdruck',
  'nn_pressure' => 'Auf NN reduz. Luftdruck',
  'dewpoint' => 'Taupunkt',
  'wind' => 'Wind',
  'speed' => 'Geschwindigkeit',
  'windspeed' => 'Windgeschwindigkeit',
  'windchill' => 'Windk&uuml;hle',
  'for' => 'f&uuml;r',
  'for_date' => 'f&uuml;r den',
  'before_date' => 'vor dem',
  'measured_at' => 'gemessen um',
  'uhr' => ' Uhr',
  'last_hour' => 'Letzte Stunde',
  'today' => 'Heute',
  'overall' => 'Gesamt',
  'indoor' => 'Innen',
  'heat_index' => 'Hitzeindex',
  'go_to' => 'Gehe zu',
  'go' => 'Gehe',
  'or' => 'oder',
  'and' => 'und',
  'of' => 'vom',
  'from' => 'aus',
  'to' => 'bis',
  'stable' => 'stabil',
  'falling' => 'Fallend',
  'rising' => 'Steigend',
  'steady' => 'Geichbleibend',
  'cloudy' => 'Wolkig',
  'sunny' => 'Sonnig',
  'rainy' => 'Regen',
  'precipation' => 'Niederschlag',
  'Precipations' => 'Niederschl&auml;ge',
  'forecast' => 'Vorhersage',
  'heat_index_not_relevant_temp' => 'Nicht relevant (Temperatur kleiner als 27 C)',
  'heat_index_not_relevant_hum' => 'Nicht relevant (Luftfeuchtigkeit kleiner als 40 %)',
  'range' => 'Zeitraum',
  'january' => 'Januar',
  'february' => 'Februar',
  'march' => 'M&auml;rz',
  'april' => 'April',
  'may' => 'Mai',
  'june' => 'Juni',
  'july' => 'Juli',
  'august' => 'August',
  'september' => 'September',
  'october' => 'Oktober',
  'november' => 'November',
  'december' => 'Dezember',
  'Jan' => 'Jan',
  'Feb' => 'Feb',
  'Mar' => 'M&auml;r',
  'Apr' => 'Apr',
  'May' => 'Mai',
  'Jun' => 'Jun',
  'Jul' => 'Jul',
  'Aug' => 'Aug',
  'Sep' => 'Sep',
  'Oct' => 'Okt',
  'Nov' => 'Nov',
  'Dec' => 'Dez',
  'date' => 'Datum',
  'time' => 'Uhrzeit',
  'dir' => 'Rich.',
  'avg' => 'Mittel',
  'min' => 'Min',
  'max' => 'Max',
  'temp' => 'Temp',
  'temp_out' => 'Temp Aus.',
  'temp_in' => 'Temp In.',
  'hum_out' => 'Feucht Aus.',
  'hum_in' => 'Feucht In.',
  '24_hours_back' => '24 Stunden zur&uuml;ck',
  '24_hours_forward' => '24 Stunden vor',
  '24_hours' => '24 Stunden',
  'statistics' => 'Statistik',
  'the_she' => 'die',
  'the_he' => 'der',
  'the_it' => 'das',
  'graphs' => 'Graphen',
  'min_values' => 'Minimalwerte',
  'max_values' => 'Maximalwerte',
  'avg_values' => 'Durchschnittswerte',
  'all_values' => 'Alle Werte',
  'show_all_values' => 'Alle Werte anzeigen',
  'to_top' => 'Nach oben',
  'temp_in_table' => 'Temp In. (&deg;C)',
  'temp_out_table' => 'Temp Aus. (&deg;C)',
  'dew_table' => 'Taup.(&deg;C)',
  'hum_in_table' => 'Hum In.(%)',
  'hum_out_table' => 'Hum Aus.(%)',
  'windspeed_table' => 'Windgeschw. (m/s)',
  'windangle_table' => 'Windrichtung (&deg;)',
  'windchill_table' => 'Windk&uuml;hle (&deg;C)',
  'winddir' => 'Windrichtung',
  'winddist' => 'Windverteilung',
  'airpressure_table' => 'Luftdruck (hPa)',
  'rain1h_table' => 'Regen 1h (mm)',
  'rain24h_table' => 'Regen 24h (mm)',
  'rainoverall_table' => 'Regen gesamt',
  'week_of' => 'die Woche von',
  'for_the_range_from' => 'f&uuml;r den Zeitraum vom',
  'warmer' => 'w&auml;rmer',
  'colder' => 'k&auml;lter',
  'north' => 'Norden',
  'northeast' => 'Nord-Ost',
  'east' => 'Osten',
  'southeast' => 'S&uuml;d-Ost',
  'south' => 'S&uuml;den',
  'southwest' => 'S&uuml;d-West',
  'west' => 'Westen',
  'northwest' => 'Nord-West',
  'unknown' => 'Unbekannt',
  'comfort' => 'Komfort',
  'comfy' => 'Behaglich',
  'still_comfy' => 'Noch behaglich',
  'awkward' => 'Unbehaglich',
  'awkwardly_wet' => 'Unbehablich feucht',
  'awkwardly_dry' => 'Unbehaglich trocken',
  'sun_position' => 'Sonnenstand',
  'sun_rise' => 'Sonnenaufgang',
  'sun_down' => 'Sonnenuntergang',
  'clima' => 'Klima',
  'climagraph' => 'Klimagraph',
  'avg_temp' => 'Temperaturmittel',
  'avg_prec' => 'Niederschlagsmittel',
  'long_avg' => 'Lang. Mittel',
  'total' => 'Gesamt',
  'yesterday' => 'Gestern',
  'at' => 'am',
  'in_the_week_from' => 'in der Woche vom',
  'in_the_period_from' => 'im Zeitraum vom',
  'north_char' => 'N',
  'east_char' => 'O',
  'south_char' => 'S',
  'west_char' => 'W',
  'outside_temperature' => 'Aussentemperatur',
  'inside_temperature' => 'Innentemperatur',
  'inside_humidity' => 'Innnenfeuchte',
  'outside_humidity' => 'Aussenfeuchte',
  'precipitation' => 'Niederschlag',
  'undefined' => 'nicht def.',
  'caution' => 'Vorsicht!',
  'extream_caution' => 'Erh&ouml;hte Vorsicht!',
  'danger' => 'Gefahr!',
  'extream_danger' => 'Erh&ouml;hte Gefahr!',
  'additionalSensors' => 'Zus&auml;tzliche Sensoren',
  'zeroMaxDays' => 'Eistag(e)',
  'zeroMaxDaysDesc' => 'H&ouml;chsttemp. h&ouml;chstens 0 &deg;C',
  'zeroMinDays' => 'Frosttag(e)',
  'zeroMinDaysDesc' => 'Tiefsttemp. h&ouml;chstens 0 &deg;C',
  'summerDays' => 'Sommertag(e)',
	'summerDaysDesc' => 'H&ouml;chsttemp. mind. 25 &deg;C',
  'heatDays' => 'Hitzetag(e)',
  'heatDaysDesc' => 'H&ouml;chsttemp. mind. 30 &deg;C',
  'tropicalNights' => 'Tropenn&auml;cht(e)',
  'tropicalNightsDesc' => 'Tiefsttemp. mind. 20 &deg;C',
  'There was' => 'Es gab',
  'Extreme values' => 'Extremwerte',
  'Climate Table' => 'Klimatafel',
  'Average' => 'Mittlere',
  'Historic' => 'Historischer',
  'Maximum Temperature' => 'H&ouml;chsttemperatur',
  'Minimum Temperature' => 'Tiefsttemperatur',
  'Peak Value' => 'H&ouml;chstwert',
  'Lowest Value' => 'Tiefstwert',
  'Raindays' => 'Regentage',

  'sensors' => array (
    'id' => "ID",
    'name' => "Name",
    'filename' => "Dateiname",
    'linenumber' => "Zeilennummer",
    'unit' => "Einheit",
    'active' => "Aktiv",
    'value' => "Aktueller Wert",
    'new' => "Neuer Sensor",
    'add' => "Sensor hinzufügen",
    'added' => "Sensor \"%s\" hinzugefügt.",
    'no_table' => "Tabelle <b>\"%s\"</b> existiert nicht.",
    'available' => "vorhanden",
    'unavailable' => "nicht vorhanden"),

  'beaufort' => array(
    'Windstille',
    'Leiser Zug',
    'Leichte Brise',
    'Schwache Brise',
    'M&auml;&szlig;ige Brise',
    'Frische Brise',
    'Starker Wind',
    'Steifer Wind',
    'St&uuml;rmischer Wind',
    'Sturm',
    'Schwerer Sturm',
    'Orkanartiger Sturm',
    'Orkan'),

  'messages' => array (
    'avg_temp' => "Die <b>mittlere Temperatur</b> im %s hat <b>%2.2f &deg;C</b> betragen.<br>",
    'avg_temp_diff' => "Damit war der Monat <b> um %2.2f &deg;C %s </b> als im langj&auml;hrigen Mittel von %2.2f &deg;C"
      . " <a href=\"http://www.dwd.de/de/FundE/Klima/KLIS/daten/online/nat/index_mittelwerte.htm\" target=\"_blank\">(mehr dazu)</a><br>",
    'max_temp' => "Die <b>h&ouml;chste Temperatur</b> wurde am <b>%s</b> um <b>%s</b> mit <b>%2.2f &deg;C</b> gemessen.<br>",
    'max_temp_short' => "Die <b>h&ouml;chste Temperatur</b> wurde am <b>%s</b> mit <b>%2.2f &deg;C</b> gemessen.<br>",
    'min_temp' => "Die <b>niedrigste Temperatur</b> trat am <b>%s</b> um <b>%s</b> mit <b>%2.2f &deg;C</b> auf.<br>",
    'min_temp_short' => "Die <b>niedrigste Temperatur</b> trat am <b>%s</b> mit <b>%2.2f &deg;C</b> auf.<br>",
    'max_temp_day' => "Der <b>w&auml;rmste Tag</b> war der <b>%s</b> mit einer Durchschnittstemperatur von <b>%2.2f &deg;C</b>.<br>",
    'min_temp_day' => "Der <b>k&auml;lteste Tag</b> war der <b>%s</b> mit durchschnittlich <b>%2.2f &deg;C</b>.<br>",
    'max_temp_month' => "Der <b>w&auml;rmste Monat</b> war der <b>%s</b> mit einer Durchschnittstemperatur von <b>%2.2f &deg;C</b>.<br>",
    'min_temp_month' => "Der <b>k&auml;lteste Monat</b> war der <b>%s</b> mit durchschnittlich <b>%2.2f &deg;C</b>.<br>",

    'avg_dewpoint' => "Die <b>Taupunktstemperatur</b> lag im Monatsdurchschnitt bei <b>%2.2f &deg;C</b>.<br>",
    'max_dewpoint' => "Der <b>h&ouml;chste Taupunkt</b> wurde am <b>%s</b> um <b>%s</b> mit <b>%2.2f &deg;C</b> erreicht.<br>",
    'min_dewpoint' => "Der <b>niedrigste Taupunkt</b> war am <b>%s</b> um <b>%s</b> mit <b>%2.2f &deg;C</b> zu verzeichnen.<br>",

    'rain_month' => "Es fielen <b>%2.2f mm Niederschlag</b>. Das waren <b>%2.2f %%</b> des langj&auml;hrigen Mittels (<b>%s mm</b>).<br>",
    'max_rain_day' => "Der <b>niederschlagsreichste Tag</b> war der <b>%s</b> mit <b>%2.2f mm</b>.<br>",
    'max_rain_month' => "Der <b>niederschlagsreichste Monat</b> war der <b>%s</b> mit <b>%2.2f mm</b>.<br>",
    'min_rain_month' => "Der <b>trockenste Monat</b> war der <b>%s</b> mit <b>%2.2f mm</b>.<br>",
    'no_rain_days' => "<b>Niederschlagsfrei</b> waren <b>%d Tage</b> (%s).<br>",

    'avg_windspeed' => "Der <b>mittlere Wind</b> im <b>%s</b> hat <b>%2.2f km/h (%s)</b> betragen.<br>",
    'max_windspeed' => "Der <b>st&auml;rkste Wind</b> war am <b>%s</b> um <b>%s</b> mit <b>%2.2f km/h (%s)</b> zu verzeichnen.<br>",
    'max_windspeed_day' => "Der <b>windigste Tag</b> war der <b>%s</b> mit einer durchschnittlichen Windgeschwindigkeit von <b>%2.2f km/h (%s)</b>.<br>",
    'min_windspeed_day' => "Am <b>wenigsten Wind</b> wehte am <b>%s</b> mit durchschnittlich <b>%2.2f km/h (%s)</b>.<br>",
    'avg_wind_dir' => "Der Wind kam vorherrschend aus <b>%s (%2.2f)</b>.<br>",

    'avg_pressure' => "Der <b>mittlere auf NN reduzierte Luftdruck</b> lag bei <b>%2.2f hPa</b>.<br>",
    'max_pressure' => "Der <b>h&ouml;chste Luftdruck</b> wurde am <b>%s</b> um <b>%s</b> mit <b>%2.2f hPa</b> gemessen.<br>",
    'max_pressure_short' => "Der <b>h&ouml;chste Luftdruck</b> wurde am <b>%s</b> mit <b>%2.2f hPa</b> gemessen.<br>",
    'min_pressure' => "Der <b>niedrigste Luftdruck</b> kam am <b>%s</b> um <b>%s</b> mit <b>%2.2f hPa</b> vor.<br>",
    'min_pressure_short' => "Der <b>niedrigste Luftdruck</b> kam am <b>%s</b> mit <b>%2.2f hPa</b> vor.<br>",
  )
);

// Now, also define alternative imgs for our use
$GLOBALS['imgsrc'] = array (
  'title' => 'graphics/title.de.png',
  'footer' => 'graphics/foot.de.jpg'
  );
?>
