<?php
////////////////////////////////////////////////////
//
// WeatherOffice
//
// http://www.sourceforge.net/projects/weatheroffice
//
// Copyright (C) 04/2007 Mathias Zuckermann &
//			 Bernhard Heibler
//
// See COPYING for license info
//
////////////////////////////////////////////////////
// Declare all text strings that we need,
// in German.
$GLOBALS['text'] = array (
  'weatherstation_in' => 'Wetterstation in ',
  'current_values' => 'Aktuelle Werte',
  'last_24_hours' => 'Letzte 24 Stunden',
  'daily_overview' => 'Tages&uuml;bersicht',
  'weekly_overview' => 'Wochen&uuml;bersicht',
  'monthly_overview' => 'Monats&uuml;bersicht',
  'yearly_overview' => 'Jahres&uuml;bersicht',
  'yearly_overview_graph' => 'Jahresübersicht',  
  'current_values' => 'Aktuelle Messwerte',
  'tendency' => 'Tendenz',
  'temperature' => 'Temperatur',
  'humidity' => 'Luftfeuchtigkeit',
  'pressure' => 'Luftdruck',
  'nn_pressure' => 'Auf NN reduz. Luftdruck',  
  'dewpoint' => 'Taupunkt',
  'wind' => 'Wind',
  'speed' => 'Geschwindigkeit',
  'windspeed' => 'Windgeschwindigkeit',
  'windchill' => 'Windk&uuml;hle',
  'for' => 'f&uuml;r',
  'for_date' => 'f&uuml;r den',
  'before_date' => 'vor dem',
  'measured_at' => 'gemessen um',
  'uhr' => ' Uhr',
  'last_hour' => 'Letzte Stunde',
  'today' => 'Heute',
  'overall' => 'Gesamt',
  'indoor' => 'Innen',
  'heat_index' => 'Hitzeindex',
  'go_to' => 'Gehe zu',
  'go' => 'Gehe',
  'or' => 'oder',
  'and' => 'und',
  'of' => 'vom',
  'from' => 'aus',
  'to' => 'bis',
  'stable' => 'stabil',
  'falling' => 'Fallend',
  'rising' => 'Steigend',
  'steady' => 'Geichbleibend',  
  'cloudy' => 'Wolkig',
  'sunny' => 'Sonnig',
  'rainy' => 'Regen',  
  'precipation' => 'Niederschlag',
  'forecast' => 'Vorhersage', 
  'heat_index_not_relevant_temp' => 'Nicht relevant (Temperatur kleiner als 27 C)',
  'heat_index_not_relevant_hum' => 'Nicht relevant (Luftfeuchtigkeit kleiner als 40 %)',
  'range' => 'Zeitraum',
  'january' => 'Januar',
  'february' => 'Februar',
  'march' => 'M&auml;rz',
  'april' => 'April',
  'may' => 'Mai',
  'june' => 'Juni',
  'july' => 'Juli',
  'august' => 'August',
  'september' => 'September',
  'october' => 'Oktober',
  'november' => 'November',
  'december' => 'Dezember',
  'date' => 'Datum',
  'time' => 'Uhrzeit',
  'dir' => 'Rich.',
  'avg' => 'Mittel',      
  'min' => 'Min',   
  'max' => 'Max',
  'temp' => 'Temp',  
  'temp_out' => 'Temp Aus.',
  'temp_in' => 'Temp In.',
  'hum_out' => 'Feucht Aus.',
  'hum_in' => 'Feucht In.',     
  '24_hours_back' => '24 Stunden zur&uuml;ck',
  '24_hours_forward' => '24 Stunden vor',
  '24_hours' => '24 Stunden',
  'statistics' => 'Statistik',  
  'the_she' => 'die',  
  'the_he' => 'der',  
  'the_it' => 'das',  
  'graphs' => 'Graphen',
  'min_values' => 'Minimalwerte',
  'max_values' => 'Maximalwerte',
  'avg_values' => 'Durchschnittswerte',
  'all_values' => 'Alle Werte',
  'show_all_values' => 'Alle Werte anzeigen',
  'to_top' => 'Nach oben',
  'temp_in_table' => 'Temp In. (&deg;C)',
  'temp_out_table' => 'Temp Aus. (&deg;C)',
  'dew_table' => 'Taup.(&deg;C)',
  'hum_in_table' => 'Hum In.(%)',
  'hum_out_table' => 'Hum Aus.(%)',
  'windspeed_table' => 'Windgeschw. (m/s)',
  'windangle_table' => 'Windrichtung (&deg;)',
  'windchill_table' => 'Windk&uuml;hle (&deg;C)',
  'winddir' => 'Windrichtung',
  'winddist' => 'Windverteilung',  
  'airpressure_table' => 'Luftdruck (hPa)',
  'rain1h_table' => 'Regen 1h (mm)',
  'rain24h_table' => 'Regen 24h (mm)',
  'rainoverall_table' => 'Regen gesamt',
  'week_of' => 'die Woche von',
  'for_the_range_from' => 'f&uuml;r den Zeitraum vom',
  'warmer' => 'w&auml;rmer',
  'colder' => 'k&auml;lter',
  'north' => 'Norden',
  'northeast' => 'Nord-Ost',
  'east' => 'Osten',
  'southeast' => 'S&uuml;d-Ost',
  'south' => 'S&uuml;den',
  'southwest' => 'S&uuml;d-West',
  'west' => 'Westen',
  'northwest' => 'Nord-West',
  'unknown' => 'Unbekannt',
  'comfort' => 'Komfort',
  'comfy' => 'Behaglich',
  'still_comfy' => 'Noch behaglich',
  'awkward' => 'Unbehaglich',
  'awkwardly_wet' => 'Unbehablich feucht',
  'awkwardly_dry' => 'Unbehaglich trocken',
  'sun_position' => 'Sonnenstand',
  'sun_rise' => 'Sonnenaufgang',
  'sun_down' => 'Sonnenuntergang',
  'climagraph' => 'Klimagraph',
  'avg_temp' => 'Temperaturmittel',
  'avg_prec' => 'Niederschlagsmittel',
  'long_avg' => 'Lang. Mittel',
  'total' => 'Gesamt',    
  'yesterday' => 'Gestern',
  'at' => 'am',
  'in_the_week_from' => 'in der Woche vom', 
  'in_the_period_from' => 'im Zeitraum vom',
  'east_char' => 'O',
  'outside_temperature' => 'Aussentemperatur',
  'inside_temperature' => 'Innentemperatur',
  'inside_humidity' => 'Innnenfeuchte',
  'outside_humidity' => 'Aussenfeuchte',
  'precipitation' => 'Niederschlag',
  'undefined' => 'nicht def.',
  'caution' => 'Vorsicht!',
  'extream_caution' => 'Erh&ouml;hte Vorsicht!', 
  'danger' => 'Gefahr!',
  'extream_danger' => 'Erh&ouml;hte Gefahr!',    
  'additionalSensors' => 'Zus&auml;tzliche Sensoren',      
  );

// Now, also define alternative imgs for our use
$GLOBALS['imgsrc'] = array (
  'title' => 'graphics/title.de.png',
  'footer' => 'graphics/foot.de.jpg'
  );
?>
