<?php
////////////////////////////////////////////////////
//
// WeatherOffice
//
// http://www.sourceforge.net/projects/weatheroffice
//
// Copyright (C) 04/2007 Mathias Zuckermann &
//			 Bernhard Heibler
//
// See COPYING for license info
//
////////////////////////////////////////////////////
// Declare all text strings that we need,
// in English.
$GLOBALS['text'] = array (
  'weatherstation_in' => 'Weatherstation in ',
  'current_values' => 'Current Values',
  'last_24_hours' => 'Last 24 Hours',
  'daily_overview' => 'Daily Overview',
  'weekly_overview' => 'Weekly Overview',
  'monthly_overview' => 'Monthly Overview',
  'yearly_overview' => 'Yearly Overview',
  'yearly_overview_graph' => 'Yearly Overview',  
  'current_values' => 'Current values',
  'tendency' => 'Tendency',
  'temperature' => 'Temperature',
  'humidity' => 'Humidity',
  'pressure' => 'Airpressure',
  'nn_pressure' => 'Airpressure reduced to NN',
  'precipitation' => 'Precipitation',
  'dewpoint' => 'Dewpoint',
  'wind' => 'Wind',
  'speed' => 'Speed',
  'windchill' => 'Windchill',
  'for' => 'for',
  'for_date' => 'for',
  'before_date' => 'before',
  'measured_at' => 'measured at',
  'uhr' => '',
  'last_hour' => 'Last Hour',
  'today' => 'Today',
  'indoor' => 'Indoor',
  'heat_index' => 'Heat Index',
  'overall' => 'Over All',
  'go_to' => 'Go to',
  'go' => 'Go',
  'or' => 'or',
  'and' => 'and',
  'of' => 'of',
  'from' => 'from',
  'to' => 'to',
  'stable' => 'stable',
  'falling' => 'Falling',
  'rising' => 'Rising',
  'steady' => 'Steady',
  'cloudy' => 'Cloudy',
  'sunny' => 'Sunny',
  'rainy' => 'Rainy',
  'forecast' => 'Forecast',   
  'heat_index_not_relevant_temp' => 'Not relevant (Temperature less than 27 C)',
  'heat_index_not_relevant_hum' => 'Not relevant (Humidity less than 40 %)',
  'range' => 'Range',
  'january' => 'January',
  'february' => 'February',
  'march' => 'March',
  'april' => 'April',
  'may' => 'May',
  'june' => 'June',
  'july' => 'July',
  'august' => 'August',
  'september' => 'September',
  'october' => 'October',
  'november' => 'November',
  'december' => 'December',
  'date' => 'Date',
  'time' => 'Time',
  'dir' => 'Dir.',  
  'avg' => 'Avg',  
  'min' => 'Min',   
  'max' => 'Max', 
  'temp' => 'Temp',  
  'temp_out' => 'Temp Out',
  'temp_in' => 'Temp In',
  'hum_out' => 'Hum Out',
  'hum_in' => 'Hum In',    
  '24_hours_back' => '24 hours back',
  '24_hours_forward' => '24 hours forward',
  '24_hours' => '24 hours',
  'statistics' => 'Statistics',
  'the_she' => 'the',  
  'the_he' => 'the',  
  'the_it' => 'the', 
  'graphs' => 'Graphs',
  'min_values' => 'Minimum Values',
  'max_values' => 'Maximum Values',
  'avg_values' => 'Average Values',
  'all_values' => 'All Values',
  'show_all_values' => 'Show all values',
  'to_top' => 'Top',
  'temp_in_table' => 'Temp In (&deg;C)',
  'temp_out_table' => 'Temp Out (&deg;C)',
  'dew_table' => 'Dew (&deg;C)',
  'hum_in_table' => 'Hum In (%)',
  'hum_out_table' => 'Hum Out (%)',
  'windspeed_table' => 'Windspeed (m/s)',
  'windangle_table' => 'Wind Angle (&deg;)',
  'windchill_table' => 'Wind Chill (&deg;C)',
  'airpressure_table' => 'Airpressure (hPa)',
  'rain1h_table' => 'Rain 1h (mm)',
  'rain24h_table' => 'Rain 24h (mm)',
  'rainoverall_table' => 'Rain overall', 
  'week_of' => 'the week of',
  'for_the_range_from' => 'for the range from',
  'warmer' => 'warmer',
  'colder' => 'colder',
  'north' => 'North',
  'northeast' => 'North-East',
  'east' => 'East',
  'southeast' => 'South-East',
  'south' => 'South',
  'southwest' => 'South-West',
  'west' => 'West',
  'northwest' => 'North-West',
  'unknown' => 'Unknown',
  'comfort' => 'Comfort',
  'comfy' => 'Comfy',
  'still_comfy' => 'Still comfy',
  'awkward' => 'Awkward',
  'awkwardly_wet' => 'Awkwardly wet',
  'awkwardly_dry' => 'Awkwardly dry',
  'sun_position' => 'Position of the sun',
  'sun_rise' => 'Sunrise',
  'sun_down' => 'Sunset',
  'climagraph' => 'Climate graph',
  'avg_temp' => 'Average Temperature',
  'avg_prec' => 'Average Precipitation',
  'long_avg' => 'Long. Avg.',
  'total' => 'Total'       
  );

// Now, also define alternative imgs for our use
$GLOBALS['imgsrc'] = array (
  'title' => 'graphics/title.en.png',
  'footer' => 'graphics/foot.en.jpg'
  );
?>
