<?php
////////////////////////////////////////////////////
//
// WeatherOffice
//
// http://www.sourceforge.net/projects/weatheroffice
//
// Copyright (C) 04/2007 Mathias Zuckermann &
//			 Bernhard Heibler
//
// English Translation Steve Chamberlin
//
// See COPYING for license info
//
////////////////////////////////////////////////////
// Declare all text strings that we need,
// in English.
$GLOBALS['text'] = array (
  'weatherstation_in' => 'Weatherstation in ',
  'current_values' => 'Current Values',
  'last_24_hours' => 'Last 24 Hours',
  'daily_overview' => 'Daily Overview',
  'weekly_overview' => 'Weekly Overview',
  'Monthly' => 'Monthly',
  'monthly_overview' => 'Monthly Overview',
  'yearly_overview' => 'Yearly Overview',
  'yearly_overview_graph' => 'Yearly Overview',
  'partial_values' => 'Preliminary data on',
  'current_values' => 'Current values',
  'tendency' => 'Tendency',
  'temperature' => 'Temperature',
  'Temperatures' => 'Temperatures',
  'humidity' => 'Humidity',
  'pressure' => 'Airpressure',
  'nn_pressure' => 'Airpressure reduced to NN',
  'precipitation' => 'Precipitation',
  'dewpoint' => 'Dewpoint',
  'wind' => 'Wind',
  'speed' => 'Speed',
  'windspeed' => 'Windspeed',
  'windchill' => 'Windchill',
  'for' => 'for',
  'for_date' => 'for',
  'before_date' => 'before',
  'measured_at' => 'measured at',
  'uhr' => '',
  'last_hour' => 'Last Hour',
  'today' => 'Today',
  'indoor' => 'Indoor',
  'heat_index' => 'Heat Index',
  'overall' => 'Over All',
  'go_to' => 'Go to',
  'go' => 'Go',
  'or' => 'or',
  'and' => 'and',
  'of' => 'of',
  'from' => 'from',
  'to' => 'to',
  'stable' => 'stable',
  'falling' => 'Falling',
  'rising' => 'Rising',
  'steady' => 'Steady',
  'cloudy' => 'Cloudy',
  'sunny' => 'Sunny',
  'rainy' => 'Rainy',
  'precipation' => 'Precipation',
  'Precipations' => 'Precipation',
  'forecast' => 'Forecast',
  'heat_index_not_relevant_temp' => 'Not relevant (Temperature less than 27 C)',
  'heat_index_not_relevant_hum' => 'Not relevant (Humidity less than 40 %)',
  'range' => 'Range',
  'january' => 'January',
  'february' => 'February',
  'march' => 'March',
  'april' => 'April',
  'may' => 'May',
  'june' => 'June',
  'july' => 'July',
  'august' => 'August',
  'september' => 'September',
  'october' => 'October',
  'november' => 'November',
  'december' => 'December',
  'Jan' => 'Jan',
  'Feb' => 'Feb',
  'Mar' => 'Mar',
  'Apr' => 'Apr',
  'May' => 'May',
  'Jun' => 'Jun',
  'Jul' => 'Jul',
  'Aug' => 'Aug',
  'Sep' => 'Sep',
  'Oct' => 'Oct',
  'Nov' => 'Nov',
  'Dec' => 'Dec',
  'date' => 'Date',
  'time' => 'Time',
  'dir' => 'Dir.',
  'avg' => 'Avg',
  'min' => 'Min',
  'max' => 'Max',
  'temp' => 'Temp',
  'temp_out' => 'Temp Out',
  'temp_in' => 'Temp In',
  'hum_out' => 'Hum Out',
  'hum_in' => 'Hum In',
  '24_hours_back' => '24 hours back',
  '24_hours_forward' => '24 hours forward',
  '24_hours' => '24 hours',
  'statistics' => 'Statistics',
  'the_she' => 'the',
  'the_he' => 'the',
  'the_it' => 'the',
  'graphs' => 'Graphs',
  'min_values' => 'Minimum Values',
  'max_values' => 'Maximum Values',
  'avg_values' => 'Average Values',
  'all_values' => 'All Values',
  'show_all_values' => 'Show all values',
  'to_top' => 'Top',
  'temp_in_table' => 'Temp In (&deg;C)',
  'temp_out_table' => 'Temp Out (&deg;C)',
  'dew_table' => 'Dew (&deg;C)',
  'hum_in_table' => 'Hum In (%)',
  'hum_out_table' => 'Hum Out (%)',
  'windspeed_table' => 'Windspeed (m/s)',
  'windangle_table' => 'Wind Angle (&deg;)',
  'windchill_table' => 'Wind Chill (&deg;C)',
  'winddir' => 'Wind Direction',
  'winddist' => 'Wind Distribution',
  'airpressure_table' => 'Airpressure (hPa)',
  'rain1h_table' => 'Rain 1h (mm)',
  'rain24h_table' => 'Rain 24h (mm)',
  'rainoverall_table' => 'Rain overall',
  'week_of' => 'the week of',
  'for_the_range_from' => 'for the range from',
  'warmer' => 'warmer',
  'colder' => 'colder',
  'north' => 'North',
  'northeast' => 'North-East',
  'east' => 'East',
  'southeast' => 'South-East',
  'south' => 'South',
  'southwest' => 'South-West',
  'west' => 'West',
  'northwest' => 'North-West',
  'unknown' => 'Unknown',
  'comfort' => 'Comfort',
  'comfy' => 'Comfy',
  'still_comfy' => 'Still comfy',
  'awkward' => 'Awkward',
  'awkwardly_wet' => 'Awkwardly wet',
  'awkwardly_dry' => 'Awkwardly dry',
  'sun_position' => 'Position of the sun',
  'sun_rise' => 'Sunrise',
  'sun_down' => 'Sunset',
  'clima' => 'Climate',
  'climagraph' => 'Climate Graph',
  'avg_temp' => 'Average Temperature',
  'avg_prec' => 'Average Precipitation',
  'long_avg' => 'Long. Avg.',
  'total' => 'Total',
  'yesterday' => 'Yesterday',
  'at' => '',
  'in_the_week_from' => 'in the week from',
  'in_the_period_from' => 'in the period from',
  'north_char' => 'N',
  'east_char' => 'E',
  'south_char' => 'S',
  'west_char' => 'W',
  'outside_temperature' => 'Outside Temperature',
  'inside_temperature' => 'Inside Temperature',
  'inside_humidity' => 'Inside Humidity',
  'outside_humidity' => 'Outside Humidity',
  'precipitation' => 'Precipitation',
  'undefined' => 'Undefined',
  'caution' => 'Caution!',
  'extream_caution' => 'Extreme Caution!',
  'danger' => 'Danger!',
  'extream_danger' => 'Extreme Danger!',
  'additionalSensors' => 'Additional Sensors',

  'zeroMaxDays' => 'ice-day(s)',
  'zeroMaxDaysDesc' => 'highest temp. max. 0 &deg;C',
  'zeroMinDays' => 'frost-day(s)',
  'zeroMinDaysDesc' => 'lowest temp. max. 0 &deg;C',
  'summerDays' => 'summer-day(s)',
	'summerDaysDesc' => 'highest temp. at least 25 &deg;C',
  'heatDays' => 'heat-day(s)',
  'heatDaysDesc' => 'highest temp. at least 30 &deg;C',
  'tropicalNights' => 'tropical night(s)',
  'tropicalNightsDesc' => 'lowest temp. at least 20 &deg;C',
  'There was' => 'There was',
  'Extreme values' => 'Extreme Values',
  'Climate Table' => 'Climate Table',
  'Average' => 'Average',
  'Maximum Temperature' => 'Maximum Temperature',
  'Minimum Temperature' => 'Minimum Temperature',
  'Historic' => 'Historic',
  'Peak Value' => 'Peak Value',
  'Lowest Value' => 'Lowest Value',
  'Raindays' => 'Raindays',

  'sensors' => array (
    'id' => "ID",
    'name' => "Name",
    'filename' => "File name",
    'linenumber' => "Line number",
    'unit' => "Unit",
    'active' => "Active",
    'value' => "Current value",
    'new' => "New Sensor",
    'add' => "Add Sensor",
    'added' => "Sensor \"%s\" added.",
    'no_table' => "Table <b>\"%s\"</b> doesn't exists.",
    'available' => "available (file ready)",
    'unavailable' => "unavailable (file not found)"),

  'beaufort' => array(
    'Calm',
    'Light Air',
    'Light Breeze',
    'Gentle Breeze',
    'Moderate Breeze',
    'Fresh Breeze',
    'Strong Breeze',
    'Near Gale',
    'Gale',
    'Strong Gale',
    'Storm',
    'Violent Storm',
    'Hurricane'),

  'messages' => array (
    'avg_temp' => "The <b>average temperature</b> was <b>%2.2f &deg;C</b> in %s.<br>",
    'avg_temp_diff' => "This means it was <b> by %2.2f &deg;C %s </b> then in the long-time average of %2.2f &deg;C"
      . " <a href=\"http://www.dwd.de/de/FundE/Klima/KLIS/daten/online/nat/index_mittelwerte.htm\" target=\"_blank\">(read more)</a><br>",
    'max_temp' => "The <b>highest temperature</b> was measured on <b>%ss</b> at <b>%s</b> with <b>%2.2f &deg;C</b>.<br>",
    'max_temp_short' => "The <b>highest temperature</b> was measured on <b>%s</b> with <b>%2.2f &deg;C</b>.<br>",
    'min_temp' => "The <b>lowest temperature</b> appeared on <b>%s</b> at <b>%s</b> and was <b>%2.2f &deg;C</b>.<br>",
    'min_temp_short' => "The <b>lowest temperature</b> appeared on <b>%s</b> and was <b>%2.2f &deg;C</b>.<br>",
    'max_temp_day' => "The <b>warmest day</b> has been the <b>%s</b> with an average temperature of <b>%2.2f &deg;C</b>.<br>",
    'min_temp_day' => "The <b>coldest day</b> was the <b>%s</b> with an average of <b>%2.2f &deg;C</b>.<br>",
    'max_temp_month' => "The <b>warmest month</b> has been <b>%s</b> with an average temperature of <b>%2.2f &deg;C</b>.<br>",
    'min_temp_month' => "The <b>coldest month</b> was <b>%s</b> with an average of <b>%2.2f &deg;C</b>.<br>",

    'avg_dewpoint' => "The <b>dewpoint</b> was in the average of the month at <b>%2.2f &deg;C</b>.<br>",
    'max_dewpoint' => "The <b>highest dewpoint</b> was reached on <b>%s</b> at <b>%s</b> with <b>%2.2f &deg;C</b>.<br>",
    'min_dewpoint' => "The <b>lowest dewpoint</b> was measured on <b>%s</b> at <b>%s</b> with <b>%2.2f &deg;C</b>.<br>",

    'rain_month' => "There was a <b>precipitation of %2.2f mm</b>, <b>%2.2f %%</b> of the long-time average of <b>%s mm</b>.<br>",
    'max_rain_day' => "The day with the <b>most precipitation</b> was <b>%s</b> with <b>%2.2f mm</b>.<br>",
    'max_rain_month' => "The month with the <b>most precipitation</b> was <b>%s</b> with <b>%2.2f mm</b>.<br>",
    'min_rain_month' => "The <b>dryest month</b> was <b>%s</b> with <b>%2.2f mm</b>.<br>",
    'no_rain_days' => "<b>No precipitation</b> happened on <b>%d day(s)</b> (%s).<br>",

    'avg_windspeed' => "The <b>average windspeed</b> in <b>%s</b> was <b>%2.2f km/h (%s)</b>.<br>",
    'max_windspeed' => "The <b>strongest wind</b> was measured on <b>%s</b> at <b>%s</b> with <b>%2.2f km/h (%s)</b>.<br>",
    'max_windspeed_day' => "The <b>windiest day</b> was <b>%s</b> with an average windspeed of <b>%2.2f km/h (%s)</b>.<br>",
    'min_windspeed_day' => "The day with the <b>least wind</b> was <b>%s</b> with an average of <b>%2.2f km/h (%s)</b>.<br>",
    'avg_wind_dir' => "The wind came most of the time from <b>%s (%2.2f)</b>.<br>",

    'avg_pressure' => "The <b>average, to normal zero reduced airpressure</b> was at <b>%2.2f hPa</b>.<br>",
    'max_pressure' => "The <b>highst airpressure</b> was measured on <b>%s</b> at <b>%s</b> with <b>%2.2f hPa</b>.<br>",
    'max_pressure_short' => "The <b>highst airpressure</b> was measured on <b>%s</b> with <b>%2.2f hPa</b>.<br>",
    'min_pressure' => "The <b>lowest airpressure</b> appeared on <b>%s</b> at <b>%s</b> with <b>%2.2f hPa</b>.<br>",
    'min_pressure_short' => "The <b>lowest airpressure</b> appeared on <b>%s</b> with <b>%2.2f hPa</b>.<br>",

    'no_data_found_d' => "No data found for the %s. Data are available between the %s and the %s.",
    'no_data_found_m' => "No data found for %s. Data are available between the %s and the %s.",
    'no_data_found_y' => "No data found for %s. Data are available between the %s and the %s.",
  )
);

// Now, also define alternative imgs for our use
$GLOBALS['imgsrc'] = array (
  'title' => 'graphics/title.en.png',
  'footer' => 'graphics/foot.en.jpg'
  );
?>
