<?php
////////////////////////////////////////////////////
//
// WeatherOffice
//
// http://www.sourceforge.net/projects/weatheroffice
//
// Copyright (C) 04/2007 Mathias Zuckermann &
//			 Bernhard Heibler
//
// English Translation Steve Chamberlin
//
// See COPYING for license info
//
////////////////////////////////////////////////////
// Declare all text strings that we need,
// in English.
$GLOBALS['text'] = array (
  'weatherstation_in' => 'Station m&eacute;t&eacute;o &agrave;',
  'current_values' => 'Valeurs actuelles',
  'last_24_hours' => 'Derni&egrave;res 24h',
  'daily_overview' => 'Aper&ccedil;u journalier',
  'weekly_overview' => 'Aper&ccedil;u hebdomadaire',
  'Monthly' => 'Mensuel',
  'monthly_overview' => 'Aper&ccedil;u mensuel',
  'yearly_overview' => 'Aper&ccedil;u annuel',
  'yearly_overview_graph' => 'Aper&ccedil;u annuel',
  'current_values' => 'Valeurs actuelles',
  'tendency' => 'Tendance',
  'temperature' => 'Temp&eacute;rature',
  'Temperatures' => 'Temp&eacute;ratures',
  'humidity' => 'Humidit&eacute;',
  'pressure' => 'Pression',
  'nn_pressure' => 'Pression absolue',
  'precipitation' => 'Pr&eacute;cipitation',
  'dewpoint' => 'Point de ros&eacute;e',
  'wind' => 'Vent',
  'speed' => 'Vitesse',
  'windspeed' => 'Vitesse du vent',
  'windchill' => 'Temp&eacute;rature ressentie',
  'for' => 'pour',
  'for_date' => 'pour le',
  'before_date' => 'avant le',
  'measured_at' => 'mesures du',
  'uhr' => '',
  'last_hour' => 'Derni&egrave;re heure',
  'today' => 'Aujourd\'hui',
  'indoor' => 'Int&eacute;rieur',
  'heat_index' => 'Heat Index',
  'overall' => 'Total',
  'go_to' => 'Aller &agrave;',
  'go' => 'Aller',
  'or' => 'ou',
  'and' => 'et',
  'of' => 'du',
  'from' => 'du',
  'to' => 'au',
  'stable' => 'Stable',
  'falling' => 'D&eacute;gradation',
  'rising' => 'Am&eacute;lioration',
  'steady' => 'Constant',
  'cloudy' => 'Nuageux',
  'sunny' => 'Ensoleill&eacute;',
  'rainy' => 'Pluvieux',
  'precipation' => 'Pr&eacute;cipitation',
  'Precipations' => 'Pr&eacute;cipitations',
  'forecast' => 'Pr&eacute;vision',
  'heat_index_not_relevant_temp' => 'Non significatif (Temperature inf&eacute;rieure &agrave; 27 C)',
  'heat_index_not_relevant_hum' => 'Non significatif (Humidit&eacute; inf&eacute;rieure &agrave; 40 %)',
  'range' => 'Intervalle',
  'january' => 'Janvier',
  'february' => 'F&eacute;vrier',
  'march' => 'Mars',
  'april' => 'Avril',
  'may' => 'Mai',
  'june' => 'Juin',
  'july' => 'Juillet',
  'august' => 'Ao&ucirc;t',
  'september' => 'Septembre',
  'october' => 'Octobre',
  'november' => 'Novembre',
  'december' => 'D&eacute;cembre',
  'Jan' => 'Janv',
  'Feb' => 'F&eacute;vr',
  'Mar' => 'Mars',
  'Apr' => 'Avr',
  'May' => 'Mai',
  'Jun' => 'Juin',
  'Jul' => 'Juil',
  'Aug' => 'Ao&ucirc;t',
  'Sep' => 'Sept',
  'Oct' => 'Oct',
  'Nov' => 'Nov',
  'Dec' => 'D&eacute;c',
  'date' => 'Date',
  'time' => 'Heure',
  'dir' => 'Dir.',
  'avg' => 'Moy',
  'min' => 'Min',
  'max' => 'Max',
  'temp' => 'Temp',
  'temp_out' => 'Temp Ext',
  'temp_in' => 'Temp Int',
  'hum_out' => 'Hum Ext',
  'hum_in' => 'Hum Int',
  '24_hours_back' => '24h avant',
  '24_hours_forward' => '24h apr&egrave;s',
  '24_hours' => '24 heures',
  'statistics' => 'Statistiques',
  'the_she' => 'les',
  'the_he' => 'le',
  'the_it' => 'le',
  'graphs' => 'Graphiques',
  'min_values' => 'Valeurs Minimum',
  'max_values' => 'Valeurs Maximum',
  'avg_values' => 'Valeurs Moyennes',
  'all_values' => 'Toues les Values',
  'show_all_values' => 'Voir toutes les valeurs',
  'to_top' => 'Haut',
  'temp_in_table' => 'Temp Int (&deg;C)',
  'temp_out_table' => 'Temp Ext (&deg;C)',
  'dew_table' => 'Ros&eacute;e (&deg;C)',
  'hum_in_table' => 'Hum Int (%)',
  'hum_out_table' => 'Hum Ext (%)',
  'windspeed_table' => 'Vitesse du vent (m/s)',
  'windangle_table' => 'Angle du vent (&deg;)',
  'windchill_table' => 'Temp. ressentie (&deg;C)',
  'winddir' => 'Direction du vent',
  'winddist' => 'R&eacute;partition du vent',
  'airpressure_table' => 'Pression (hPa)',
  'rain1h_table' => 'Pluie 1h (mm)',
  'rain24h_table' => 'Pluis 24h (mm)',
  'rainoverall_table' => 'Pluie totale',
  'week_of' => 'la semaine du',
  'for_the_range_from' => 'pour la p&eacute;riode du',
  'warmer' => 'plus chaud',
  'colder' => 'plus froid',
  'north' => 'Nord',
  'northeast' => 'Nord-Est',
  'east' => 'Est',
  'southeast' => 'Sud-Est',
  'south' => 'Sud',
  'southwest' => 'Sud-Ouest',
  'west' => 'Ouest',
  'northwest' => 'Nord-Ouest',
  'unknown' => 'Inconnu',
  'comfort' => 'Confort',
  'comfy' => 'Calme',
  'still_comfy' => 'Toujours calme',
  'awkward' => 'Awkward',
  'awkwardly_wet' => 'Awkwardly wet',
  'awkwardly_dry' => 'Awkwardly dry',
  'sun_position' => 'Soleil',
  'sun_rise' => 'Lever',
  'sun_down' => 'Coucher',
  'clima' => 'Climat',
  'climagraph' => 'Graphique Climatique',
  'avg_temp' => 'Temp&eacute;rature Moyenne',
  'avg_prec' => 'Pr&eacute;cipitation Moyenne',
  'long_avg' => 'Long. Avg.',
  'total' => 'Total',
  'yesterday' => 'Hier',
  'at' => '',
  'in_the_week_from' => 'la semaine du',
  'in_the_period_from' => 'p&eacute;riode du',
  'east_char' => 'E',
  'outside_temperature' => 'Temp&eacute;rature Ext&eacute;rieure',
  'inside_temperature' => 'Temp&eacute;rature Int&eacute;rieure',
  'inside_humidity' => 'Humidit&eacute; Int&eacute;rieure',
  'outside_humidity' => 'Humidit&eacute; Ext&eacute;rieure',
  'precipitation' => 'Pr&eacute;cipitation',
  'undefined' => 'Non d&eacute;fini',
  'caution' => 'Attention!',
  'extream_caution' => 'Attention extr&ecirc;me!',
  'danger' => 'Danger!',
  'extream_danger' => 'Danger extr&ecirc;me!',
  'additionalSensors' => 'Capteur Additionnel',

  'zeroMaxDays' => 'jour(s) sans d&eacutegel (ice-day(s))',
  'zeroMaxDaysDesc' => 'temp. maxi inf. &agrave; 0 &deg;C',
  'zeroMinDays' => 'jour(s) de gel (frost-day(s))',
  'zeroMinDaysDesc' => 'temp. mini inf. &agrave; 0 &deg;C',
  'summerDays' => 'jour(s) d\'&eacute;t&eacute; (summer-day(s))',
  'summerDaysDesc' => 'temp. maxi sup. &agrave; 25 &deg;C',
  'heatDays' => 'jour(s) de canicule (heat-day(s))',
  'heatDaysDesc' => 'temp. maxi sup. &agrave; 30 &deg;C',
  'tropicalNights' => 'nuit(s) tropicale(s) (tropical night(s)',
  'tropicalNightsDesc' => 'temp. mini sup. &agrave; 20 &deg;C',
  'There was' => 'Il y a eu',
  'Extreme values' => 'Valeurs Extr&ecirc;mes',
  'Climate Table' => 'Table Climatique',
  'Average' => 'Moyenne',
  'Maximum Temperature' => 'Temperature Maximum',
  'Minimum Temperature' => 'Temperature Minimum',
  'Historic' => 'Historique',
  'Peak Value' => 'Valeur la plus haute',
  'Lowest Value' => 'Valeur la plus basse',
  'Raindays' => 'Jours de pluie'
  );

// Now, also define alternative imgs for our use
$GLOBALS['imgsrc'] = array (
  'title' => 'graphics/title.fr.png',
  'footer' => 'graphics/foot.fr.jpg'
  );
?>
